#!/usr/bin/env bash
git init
git add .
git commit -m "first commit"
git branch -M main
git remote add origin git@github.com:Fernal73/CheckStyleBug.git
git push -u origin main
git branch development
git checkout development
git push -u
